### PR TITLE
fix: camel case generated lint rule names

### LINKED ISSUE #456: jsxA11Y casing autogenerated in packages/@romejs/js-compiler/lint/rules/index.ts
Description:

when I run `node scripts/lint/add.cjs aRule react`, the auto generated file keeps changing the spelling of the rules prefixed with node `jsxA11y`. Master has capital Y `jsxA11Y` which doesn't match the lowercase y in the pathname. I'm for matching the pathname, so if it's capital Y in pathname, then same for the rule name, and if lowercase Y, then match in pathname and rulename.

## Steps To Reproduce

1. run `node scripts/lint/add.cjs aRule react`
2. check packages/@romejs/js-compiler/lint/rules/index.ts

Screen Shot 2020-05-17 at 12 36 56 PM

## Expected Results

The updated file shouldn't affect those lines

### PR DESCRIPTION
**Pull request by bitpshr**
This pull request updates the generation script for adding new lint rules by camel casing generated filenames in the same way that internal linting does.

Resolves #456

### CODE REVIEW

File: scripts/_utils.cjs [hunk 1]
```diff
@@ -102,3 +102,28 @@ exports.readGeneratedFile = function(loc) {
 	file += "\n\n";
 	return file;
 };
+
+exports.toCamelCase = function(str, forceCapitalize) {
```
Comment (bitpshr) [inline scripts/_utils.cjs:106]: The duplication with `@romejs/string-utils/toCamelCase` is not ideal. If this becomes more common, we can formalize a proper approach to share functionality between the CJS scripts and the core TS packages.

**Comment by sebmck** [comment]
Looks good to me. I agree the duplication isn't ideal. Thank you!
