### PR TITLE
fix: transpile typescript enums

### LINKED ISSUE #534: Rome should support TypeScript enums
## Description:

Rome does not handle TypeScript enums properly. Compilation strips enums in the same way types are stripped, causing the resulting code to fail.

## Steps To Reproduce

    >    echo 'enum Foo { bar }; console.log(Foo.bar);' > bug.ts
    >    rome run bug.ts
    
         ReferenceError: ___R$$priv$project$rome$bug_ts$Foo is not defined

## Expected Results

Rome should not crash and should output the underlying enum value for `Foo.bar`.

### PR DESCRIPTION
**Pull request by bitpshr**
This pull request adds a new module to transpile TypeScript enums. Functionality matches the TypeScript compiler and the related Babel transform.

Resolves #534
Supersedes #536

**Examples:**

Input:
```ts
enum Test1 {a, b}

enum Test2 {a = 3, b = 10}

enum Test3 {a = "foo", b = "bar"}

enum Test4 {a = 7, b = "bar"}

enum Test5 {a = 5 + 5, b}

enum Test6 {a = 5 + 5, b = a}
````

Output:
```ts
function(Test1) {
	Test1[Test1["a"] = 0] = "a"
	Test1[Test1["b"] = 1] = "b"
}(Test1 || (Test1 = {}))

function(Test2) {
	Test2[Test2["a"] = 3] = "a"
	Test2[Test2["b"] = 10] = "b"
}(Test2 || (Test2 = {}))

function(Test3) {
	Test3["a"] = "foo"
	Test3["b"] = "bar"
}(Test3 || (Test3 = {}))

function(Test4) {
	Test4[Test4["a"] = 7] = "a"
	Test4["b"] = "bar"
}(Test4 || (Test4 = {}))

function(Test5) {
	Test5[Test5["a"] = 10] = "a"
	Test5[Test5["b"] = 11] = "b"
}(Test5 || (Test5 = {}))

function(Test6) {
	Test5[Test6["a"] = 10] = "a"
	Test5[Test6["b"] = 10] = "b"
}(Test6 || (Test6 = {}))
```

### CODE REVIEW

File: packages/@romejs/compiler/transforms/compile/transpile/enums.ts [hunk 1]
```diff
@@ -0,0 +1,248 @@
...
+	name: "enums",
+	enter(path: Path) {
+		const {node} = path;
+
+		if (node.type !== "TSEnumDeclaration") {
+			return node;
+		}
+
+		if (node.const) {
+			throw new Error('"const" enums are not supported');
```
Comment (sebmck) [inline packages/@romejs/compiler/transforms/compile/transpile/enums.ts:219]: Might be better to just make this emit a diagnostic, and return `REDUCE_REMOVE`. Diagnostics emitted by the compiler will be build-blocking.

File: packages/@romejs/compiler/transforms/compile/transpile/enums.ts [hunk 2]
```diff
@@ -0,0 +1,248 @@
...
+			case "-":
+				return left - right;
+			case "%":
+				return left % right;
+			default:
+				return undefined;
+		}
+	}
+}
+
```
Comment (sebmck) [inline packages/@romejs/compiler/transforms/compile/transpile/enums.ts:208]: I understand why this is necessary but it would be nice to move it into a method inside of `js-ast-utils`. Maybe `tryStaticEvaluation` or something. Babel has something similar where you can call `path.evaluate();` and it will return `{value: any; bailed: boolean;}`. `bailed` indicates that the `value` wasn't able to be derived with 100% certainty. This would be useful in a lot of other places. It could be further extended in the future.

File: packages/@romejs/compiler/transforms/compile/transpile/enums.ts [hunk 3]
```diff
@@ -0,0 +1,248 @@
...
+	isString: boolean,
+	id: JSBindingIdentifier,
+	name: string,
+	value: AnyJSExpression,
+): AnyJSExpression {
+	return (isString ? buildStringAssignment : buildNumericAssignment)(
+		id,
+		name,
+		value,
+	);
```
Comment (ooflorent) [inline packages/@romejs/compiler/transforms/compile/transpile/enums.ts:43]: I think this is unnecessary _complex_.
Could you change it this way?

```suggestion
return isString
  ? buildStringAssignment(id, name, value)
  : buildNumericAssignment(id, name, value);
```

File: packages/@romejs/compiler/transforms/compile/transpile/enums.ts [hunk 4]
```diff
@@ -0,0 +1,248 @@
...
+		const left = Number(evalConstant(expr.left));
+		if (left === undefined) {
+			return;
+		}
+		const right = Number(evalConstant(expr.right));
+		if (right === undefined) {
+			return;
+		}
+
+		switch (expr.operator) {
```
Comment (ooflorent) [inline packages/@romejs/compiler/transforms/compile/transpile/enums.ts:180]: Exponential operator is missing.
Logical operators are also supported by TypeScript but I don't see the value.

Comment (bitpshr) [reply packages/@romejs/compiler/transforms/compile/transpile/enums.ts:180]: I didn't think that exponential or logical operators were actually supported for enum key compile-time evaluation:

> The enum member is initialized with a constant enum expression. A constant enum expression is a subset of TypeScript expressions that can be fully evaluated at compile time. An expression is a constant enum expression if it is:
>
> a literal enum expression (basically a string literal or a numeric literal)
> a reference to previously defined constant enum member (which can originate from a different enum)
> a parenthesized constant enum expression
> * one of the +, -, ~ unary operators applied to constant enum expression
> * +, -, *, /, %, <<, >>, >>>, &, |, ^ binary operators with constant enum expressions as operands

**Comment by bitpshr** [comment]
Apologies for the radio silence here @sebmck and @ooflorent, this should be ready for another pass.

File: packages/@romejs/compiler/transforms/compile/transpile/enums.ts [hunk 5]
```diff
@@ -0,0 +1,164 @@
...
+	[name: string]: number | string;
+}
+
+function buildEnumWrapper(
+	id: JSBindingIdentifier,
+	assignments: Array<AnyJSExpression>,
+): AnyJSExpression {
+	const expressionStatement = (template.expression`
+		(function (${id}) {})(${id} || (${id} = {}));
+	` as JSCallExpression);
```
Comment (sebmck) [inline packages/@romejs/compiler/transforms/compile/transpile/enums.ts:26]: For some added safety:

```suggestion
	const expressionStatement = jsCallExpression.assert(template.expression`
		(function (${id}) {})(${id} || (${id} = {}));
	`);
```

File: packages/@romejs/compiler/transforms/compile/transpile/enums.ts [hunk 6]
```diff
@@ -0,0 +1,164 @@
+import {
+	AnyJSExpression,
+	AnyJSStatement,
+	JSBindingIdentifier,
+	JSCallExpression,
+	JSFunctionExpression,
+	TSEnumDeclaration,
+	jsNumericLiteral,
+	jsStringLiteral,
```
Comment (sebmck) [inline packages/@romejs/compiler/transforms/compile/transpile/enums.ts:9]:
```suggestion
	jsNumericLiteral,
	jsStringLiteral,
	jsCallExpression,
```

**Comment by sebmck** [comment]
Looks good, thank you!
