### PR TITLE
Linter: Handle deleted paths

### LINKED ISSUE #652: LSPServer doesn't clear diagnostics for deleted files
## Steps To Reproduce

Run `./scripts/run-vscode-extension` and wait for the Rome extension to output that it's watching.

Add an error to an existing file so that Rome publishes a diagnostic in the `Problems` tab.

Delete that file.

## Results

The diagnostic remains published for that deleted file in the `Problems` tab.

### PR DESCRIPTION
**Pull request by sebmck**
Closes #652

Not really sure how to effectively integration test this.

### CODE REVIEW

File: packages/@romejs/core/common/FileNotFound.ts [hunk 1]
```diff
@@ -1,5 +1,15 @@
 import {AbsoluteFilePath} from "@romejs/path";
 
+type MissingReturn<T> =
```
Comment (sebmck) [inline packages/@romejs/core/common/FileNotFound.ts:3]: Found myself wanting to just check if it was missing so turned it into a structured object.

File: packages/@romejs/core/server/linter/Linter.ts [hunk 2]
```diff
@@ -385,16 +397,11 @@ class LintRunner {
 
 		// We can't just use getDiagnosticFilenames as we need to produce empty arrays for removed diagnostics
 		for (const path of updatedPaths) {
-			const ref = this.request.server.projectManager.getFileReference(path);
-			const diagnostics: Diagnostics = [
-				...(diagnosticsByFilename.get(ref.uid) || []),
-				...(diagnosticsByFilename.get(ref.real.join()) || []),
-			];
```
Comment (sebmck) [inline packages/@romejs/core/server/linter/Linter.ts:392]: This was handling for diagnostics that were set as UIDs, but that isn't necessary because any diagnostics containing UIDs were already normalized and converted to absolute paths

This conversion happens as `DiagnosticsProcessor` used here has been passed `markupOptions` that contains the `normalizeFilename` prop which then passes it to `DiagnosticsNormalizer` that it calls to normalize diagnostics and will convert the filenames contained in the diagnostic as it's added.

If you're interested in learning more or can't follow the code yourself then happy to clarify. The motivation for all these UIDs and normalization is so that diagnostics can be cached without needing absolute paths. That allows our cache to be shared amongst machines and cached over a network which is a critical requirement for build performance at scale.

It does introduce significant complexity though.

**Comment by sebmck** [comment]
@yassere Feel free to merge if you're happy with the changes.
